import os
from dotenv import load_dotenv

load_dotenv()

APP_ENV = os.getenv("APP_ENV", "development")

SERVICENOW_BASE_URL = os.getenv("SERVICENOW_BASE_URL").rstrip("/")

SERVICENOW_DRY_RUN = os.getenv("SERVICENOW_DRY_RUN").lower()

SERVICENOW_INCIDENT_API_PATH = os.getenv("SERVICENOW_INCIDENT_API_PATH")

SERVICENOW_CLIENT_ID = os.getenv("SERVICENOW_CLIENT_ID")

SERVICENOW_CLIENT_SECRET = os.getenv("SERVICENOW_CLIENT_SECRET")

SERVICENOW_TOKEN_URL = os.getenv("SERVICENOW_TOKEN_URL",f"{SERVICENOW_BASE_URL}/oauth_token.do")

SERVICENOW_USERNAME = os.getenv("SERVICENOW_USERNAME")

SERVICENOW_PASSWORD = os.getenv("SERVICENOW_PASSWORD")

SERVICENOW_ASSIGNMENT_GROUP_ID = os.getenv("SERVICENOW_ASSIGNMENT_GROUP_ID")

TEAMS_WEBHOOK_URL = os.getenv("TEAMS_WEBHOOK_URL")