name: Incident Reporter

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: incident-reporter
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure processed state file exists
        run: |
          if [ ! -f processed_incidents.json ]; then
            echo "{}" > processed_incidents.json
          fi

      - name: Run Incident Monitor
        env:
          APP_ENV: ${{ secrets.APP_ENV }}

          SERVICENOW_ASSIGNMENT_GROUP_ID: ${{ secrets.SERVICENOW_ASSIGNMENT_GROUP_ID }}
          SERVICENOW_BASE_URL: ${{ secrets.SERVICENOW_BASE_URL }}
          SERVICENOW_CLIENT_ID: ${{ secrets.SERVICENOW_CLIENT_ID }}
          SERVICENOW_CLIENT_SECRET: ${{ secrets.SERVICENOW_CLIENT_SECRET }}
          SERVICENOW_INCIDENT_API_PATH: ${{ secrets.SERVICENOW_INCIDENT_API_PATH }}
          SERVICENOW_PASSWORD: ${{ secrets.SERVICENOW_PASSWORD }}
          SERVICENOW_TOKEN_URL: ${{ secrets.SERVICENOW_TOKEN_URL }}
          SERVICENOW_USERNAME: ${{ secrets.SERVICENOW_USERNAME }}

          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          python main.py

      - name: Commit processed incident state
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add processed_incidents.json

          if git diff --cached --quiet; then
            echo "No processed incident state changes to commit."
          else
            git commit -m "Update processed incident state"
            git pull --rebase
            git push
          fi
