name: Incident Reporter

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          SN_USERNAME: ${{ secrets.SN_USERNAME }}
          SN_PASSWORD: ${{ secrets.SN_PASSWORD }}
          CLIENT_AUTH: ${{ secrets.CLIENT_AUTH }}
        run: |
          python main.py
