name: Incident Reporter

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script
        env:
          APP_ENV: ${{ secrets.APP_ENV }}
          SERVICENOW_ASSIGNMENT_GROUP_ID: ${{ secrets.SERVICENOW_ASSIGNMENT_GROUP_ID }}
          SERVICENOW_BASE_URL: ${{ secrets.SERVICENOW_BASE_URL }}
          SERVICENOW_CLIENT_ID: ${{ secrets.SERVICENOW_CLIENT_ID }}
          SERVICENOW_CLIENT_SECRET: ${{ secrets.SERVICENOW_CLIENT_SECRET }}
          SERVICENOW_DRY_RUN: ${{ secrets.SERVICENOW_DRY_RUN }}
          SERVICENOW_INCIDENT_API_PATH: ${{ secrets.SERVICENOW_INCIDENT_API_PATH }}
          SERVICENOW_PASSWORD: ${{ secrets.SERVICENOW_PASSWORD }}
          SERVICENOW_TOKEN_URL: ${{ secrets.SERVICENOW_TOKEN_URL }}
          SERVICENOW_USERNAME: ${{ secrets.SERVICENOW_USERNAME }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          python main.py
